#!/bin/bash
echo $(( $(echo $WATER | tr 'water' '01234') + $(echo $STIR | tr 'stir' '0123') )) | awk 'function tobase(n,b,a,s){while(n>0){s=substr(a,n%b+1,1)s;n=int(n/b)}return s?s:substr(a,1,1)}{print tobase($1,7,"bestchol")}'
